plugins { id 'com.android.application' }

android { namespace 'com.yarikfanfarik.veryhardbell'; compileSdk 35
    defaultConfig { applicationId 'com.yarikfanfarik.veryhardbell'; minSdk 23; targetSdk 35; versionCode 2; versionName '2.0' }
}

dependencies {
    implementation 'com.google.mlkit:image-labeling:17.0.9'
}
