package com.yarikfanfarik.veryhardbell;

import android.app.*;import android.os.*;import android.content.*;import android.content.pm.PackageManager;import android.graphics.*;import android.hardware.*;import android.provider.MediaStore;import android.view.*;import android.widget.*;import java.util.*;

public class AlarmActivity extends Activity implements SensorEventListener{
 int[] order; int at=0; ArrayList<Integer> tasks=new ArrayList<>(); int diff; TextView title; LinearLayout root; SensorManager sm; long lastShake;
 @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON|WindowManager.LayoutParams.FLAG_DISMISS_KEYGUARD|WindowManager.LayoutParams.FLAG_SHOW_WHEN_LOCKED|WindowManager.LayoutParams.FLAG_TURN_SCREEN_ON);load();startTask();}
 void load(){String s=getSharedPreferences("bell",0).getString("order","0,1,2,3,4,5,6,7"),e=getSharedPreferences("bell",0).getString("enabled","11111111");diff=getSharedPreferences("bell",0).getInt("diff",0);for(String x:s.split(","))try{int i=Integer.parseInt(x);if(i>=0&&i<8&&i<e.length()&&e.charAt(i)=='1')tasks.add(i);}catch(Exception z){}if(tasks.size()==0)tasks.add(0);}
 void ui(String head){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(18,18,18,18);title=new TextView(this);title.setText(head);title.setTextSize(26);root.addView(title);ScrollView sv=new ScrollView(this);sv.addView(root);setContentView(sv);}
 Button b(String s){Button x=new Button(this);x.setText(s);return x;}
 void next(){at++;if(at>=tasks.size()){ui("🎉 Готово!");root.addView(text("Ты победил будильник. Можно снова спать 😎",24));Button x=b("Закрыть");root.addView(x);x.setOnClickListener(v->finish());return;}startTask();}
 TextView text(String s,int z){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setPadding(20,20,20,20);return t;}
 void startTask(){int t=tasks.get(at);switch(t){case 0:flappy();break;case 1:math();break;case 2:photo();break;case 3:memory();break;case 4:reaction();break;case 5:sequence();break;case 6:colorTask();break;case 7:shake();break;}}
 void flappy(){ui("🐦 Flappy — пройди 10 зелёных труб");root.addView(text("Тапай по экрану, чтобы птица летела вверх. Пройди все 10 пар зелёных труб без столкновения.",17));FlappyView v=new FlappyView(this);root.addView(v,new LinearLayout.LayoutParams(-1,0,1));v.setOnWin(this::next);}
 void math(){ui("🧮 5 примеров для 3 класса");root.addView(text(diff==0?"Легко":diff==1?"Нормально":"Сложнее",17));ArrayList<String[]> qs=new ArrayList<>();Random r=new Random();for(int i=0;i<5;i++){int a,b,op;if(diff==0){a=r.nextInt(30)+1;b=r.nextInt(20)+1;op=r.nextInt(2);}else if(diff==1){a=r.nextInt(80)+10;b=r.nextInt(50)+1;op=r.nextInt(3);}else{a=r.nextInt(90)+10;b=r.nextInt(80)+1;op=r.nextInt(4);}int ans=op==0?a+b:op==1?a-b:op==2?a*b:(b==0?0:a/b);String sym=op==0?"+":op==1?"−":op==2?"×":"÷";if(op==3){a=ans*b;ans=b==0?0:a/b;}qs.add(new String[]{a+" "+sym+" "+b+" = ?",String.valueOf(ans)});}LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);root.addView(box);for(String[]q:qs){EditText in=new EditText(this);in.setInputType(2);in.setHint(q[0]);box.addView(in);in.setTag(q[1]);}Button ok=b("Проверить 5 ответов");root.addView(ok);ok.setOnClickListener(v->{boolean good=true;for(int i=0;i<box.getChildCount();i++){EditText in=(EditText)box.getChildAt(i);if(!in.getText().toString().trim().equals(in.getTag()))good=false;}if(good)next();else Toast.makeText(this,"Есть ошибка — проверь примеры",Toast.LENGTH_SHORT).show();});}
 void photo(){ui("📷 Фото предмета");root.addView(text("Сфотографируй любой предмет вокруг себя.",18));Button take=b("Открыть камеру");root.addView(take);ImageView img=new ImageView(this);root.addView(img,new LinearLayout.LayoutParams(-1,500));take.setOnClickListener(v->{if(Build.VERSION.SDK_INT>=23&&checkSelfPermission("android.permission.CAMERA")!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{"android.permission.CAMERA"},9);else openCamera();});}
 void openCamera(){Intent i=new Intent(MediaStore.ACTION_IMAGE_CAPTURE);startActivityForResult(i,10);}
 @Override protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(r==10&&c==RESULT_OK){Toast.makeText(this,"Фото принято!",Toast.LENGTH_SHORT).show();next();}}
 @Override public void onRequestPermissionsResult(int r,String[]p,int[]g){super.onRequestPermissionsResult(r,p,g);if(r==9&&g.length>0&&g[0]==0)openCamera();}
 void memory(){ui("🧠 Память — повтори 6 плиток");root.addView(text("Запомни подсвеченные кнопки, затем нажми их в том же порядке.",17));LinearLayout grid=new LinearLayout(this);grid.setOrientation(LinearLayout.VERTICAL);root.addView(grid);ArrayList<Button> bs=new ArrayList<>();for(int i=0;i<12;i++){if(i%3==0){LinearLayout row=new LinearLayout(this);grid.addView(row);for(int j=0;j<4;j++){Button q=b("□");q.setTag(i+j);row.addView(q,new LinearLayout.LayoutParams(0,90,1));bs.add(q);i++;}i--;} }Random r=new Random();ArrayList<Integer> seq=new ArrayList<>();while(seq.size()<6){int x=r.nextInt(12);if(!seq.contains(x))seq.add(x);}new Handler().postDelayed(()->{for(int x:seq)bs.get(x).setText("🟩");new Handler().postDelayed(()->{for(Button q:bs)q.setText("□");final int[] k={0};for(Button q:bs)q.setOnClickListener(v->{int x=bs.indexOf(v);if(x==seq.get(k[0])){k[0]++;if(k[0]==6)next();}else Toast.makeText(this,"Сброс — запомни порядок ещё раз",Toast.LENGTH_SHORT).show();});},1200);},500);}
 void reaction(){ui("⚡ Реакция");TextView t=text("Жди… не нажимай!",22);root.addView(t);Button hit=b("НЕ НАЖИМАТЬ");root.addView(hit);long wait=1200+new Random().nextInt(2800);hit.setEnabled(false);new Handler().postDelayed(()->{t.setText("🟢 СЕЙЧАС!");hit.setEnabled(true);long start=System.currentTimeMillis();hit.setOnClickListener(v->{long ms=System.currentTimeMillis()-start;Toast.makeText(this,""+ms+" мс",Toast.LENGTH_SHORT).show();next();});},wait);}
 void sequence(){ui("🔢 Порядок");root.addView(text("Нажми числа от 1 до 10 по порядку.",18));ArrayList<Integer>a=new ArrayList<>();for(int i=1;i<=10;i++)a.add(i);Collections.shuffle(a);GridLayout g=new GridLayout(this);g.setColumnCount(2);root.addView(g);final int[]n={1};for(int x:a){Button q=b(String.valueOf(x));g.addView(q,new ViewGroup.LayoutParams(0,80));q.setOnClickListener(v->{if(Integer.parseInt(q.getText().toString())==n[0]){q.setEnabled(false);n[0]++;if(n[0]==11)next();}else Toast.makeText(this,"Нужна цифра "+n[0],Toast.LENGTH_SHORT).show();});}}
 void colorTask(){ui("🎨 Цвет");String[] names={"КРАСНЫЙ","СИНИЙ","ЗЕЛЁНЫЙ","ЖЁЛТЫЙ"};int[] cols={Color.RED,Color.BLUE,Color.GREEN,Color.YELLOW};Random r=new Random();for(int k=0;k<5;k++){int target=r.nextInt(4);TextView q=text("Найди: "+names[target],20);root.addView(q);LinearLayout row=new LinearLayout(this);root.addView(row);for(int j=0;j<4;j++){Button x=b(names[j]);x.setTextColor(Color.BLACK);x.setBackgroundColor(cols[j]);row.addView(x,new LinearLayout.LayoutParams(0,70,1));final int jj=j;x.setOnClickListener(v->{if(jj==target){q.setText("✓ "+names[target]);for(int z=0;z<row.getChildCount();z++)row.getChildAt(z).setEnabled(false);} });}}
 Button done=b("Готово");root.addView(done);done.setOnClickListener(v->next());}
 void shake(){ui("📳 Тряска");root.addView(text("Потряси телефон 8 раз — достаточно сильно, но аккуратно.",20));sm=(SensorManager)getSystemService(SENSOR_SERVICE);Sensor s=sm.getDefaultSensor(Sensor.TYPE_ACCELEROMETER);if(s!=null)sm.registerListener(this,s,SensorManager.SENSOR_DELAY_GAME);}
 int shakes=0;@Override public void onSensorChanged(SensorEvent e){float g=(float)Math.sqrt(e.values[0]*e.values[0]+e.values[1]*e.values[1]+e.values[2]*e.values[2]);if(g>18&&System.currentTimeMillis()-lastShake>350){lastShake=System.currentTimeMillis();shakes++;title.setText("📳 Тряска: "+shakes+"/8");if(shakes>=8){sm.unregisterListener(this);next();}}}
 @Override public void onAccuracyChanged(Sensor s,int a){}
}
