package com.yarikfanfarik.veryhardbell;

import android.app.*;import android.os.*;import android.content.*;import android.content.pm.PackageManager;import android.graphics.*;import android.hardware.*;import android.provider.MediaStore;import android.view.*;import android.widget.*;import java.util.*;
import com.google.mlkit.vision.common.InputImage;import com.google.mlkit.vision.label.ImageLabel;import com.google.mlkit.vision.label.ImageLabeling;import com.google.mlkit.vision.label.defaults.ImageLabelerOptions;

public class AlarmActivity extends Activity implements SensorEventListener{
 int at=0;ArrayList<Integer> tasks=new ArrayList<>();int diff;TextView title;LinearLayout root;SensorManager sm;long lastShake;String targetObject;Random random=new Random();
 static final String[] OBJECTS={"Холодильник","Микроволновка","Стол","Кофеварка","Телевизор","Стул","Дверь","Лампа"};
 @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON|WindowManager.LayoutParams.FLAG_DISMISS_KEYGUARD|WindowManager.LayoutParams.FLAG_SHOW_WHEN_LOCKED|WindowManager.LayoutParams.FLAG_TURN_SCREEN_ON);getWindow().getDecorView().setSystemUiVisibility(5894);load();startTask();}
 @Override public void onBackPressed(){} 
 void load(){String s=getSharedPreferences("bell",0).getString("order","0,1,2,3,4,5,6,7"),e=getSharedPreferences("bell",0).getString("enabled","11111111");diff=getSharedPreferences("bell",0).getInt("diff",0);for(String x:s.split(","))try{int i=Integer.parseInt(x);if(i>=0&&i<8&&i<e.length()&&e.charAt(i)=='1')tasks.add(i);}catch(Exception z){}if(tasks.size()==0)tasks.add(0);}
 void ui(String head){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(18,18,18,18);title=new TextView(this);title.setText(head);title.setTextSize(26);root.addView(title);ScrollView sv=new ScrollView(this);sv.addView(root);setContentView(sv);getWindow().getDecorView().setSystemUiVisibility(5894);}
 Button b(String s){Button x=new Button(this);x.setText(s);return x;}TextView text(String s,int z){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setPadding(20,20,20,20);return t;}
 void next(){at++;if(at>=tasks.size()){finishChallenge();return;}startTask();}
 void startTask(){switch(tasks.get(at)){case 0:flappy();break;case 1:math();break;case 2:photo();break;case 3:memory();break;case 4:reaction();break;case 5:sequence();break;case 6:colorTask();break;case 7:shake();break;}}
 void flappy(){ui("🐦 FLAPPY — 10 зелёных труб");root.addView(text("Тапай по экрану. Пройди все 10 пар труб. Ошибка = начать заново.",17));FlappyView v=new FlappyView(this);root.addView(v,new LinearLayout.LayoutParams(-1,700));v.setOnWin(this::next);}
 void math(){ui("🧮 5 примеров");root.addView(text(diff==0?"Легко":diff==1?"Нормально":"Сложнее",17));ArrayList<String[]>qs=new ArrayList<>();Random r=new Random();for(int i=0;i<5;i++){int a,b,op;if(diff==0){a=r.nextInt(30)+1;b=r.nextInt(20)+1;op=r.nextInt(2);}else if(diff==1){a=r.nextInt(80)+10;b=r.nextInt(50)+1;op=r.nextInt(3);}else{a=r.nextInt(90)+10;b=r.nextInt(80)+1;op=r.nextInt(4);}int ans=op==0?a+b:op==1?a-b:op==2?a*b:(a/b);String sym=op==0?"+":op==1?"−":op==2?"×":"÷";if(op==3){b=Math.max(1,b);a=ans*b;}qs.add(new String[]{a+" "+sym+" "+b+" = ?",String.valueOf(ans)});}LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);root.addView(box);for(String[]q:qs){EditText in=new EditText(this);in.setInputType(2);in.setHint(q[0]);box.addView(in);in.setTag(q[1]);}Button ok=b("Проверить");root.addView(ok);ok.setOnClickListener(v->{boolean good=true;for(int i=0;i<box.getChildCount();i++){EditText in=(EditText)box.getChildAt(i);if(!in.getText().toString().trim().equals(in.getTag()))good=false;}if(good)next();else Toast.makeText(this,"Есть ошибка",Toast.LENGTH_SHORT).show();});}
 void photo(){ui("📷 Найди предмет");String s=getSharedPreferences("bell",0).getString("objects","11111111");ArrayList<String> choices=new ArrayList<>();for(int i=0;i<OBJECTS.length;i++)if(i<s.length()&&s.charAt(i)=='1')choices.add(OBJECTS[i]);if(choices.size()==0)choices.add("Стол");targetObject=choices.get(random.nextInt(choices.size()));root.addView(text("Случайный предмет: СФОТОГРАФИРУЙ «"+targetObject.toUpperCase(Locale.getDefault())+"».\nПриложение попробует распознать его автоматически.",18));Button take=b("📷 Сфотографировать");root.addView(take);TextView result=text("",17);root.addView(result);take.setOnClickListener(v->{if(Build.VERSION.SDK_INT>=23&&checkSelfPermission("android.permission.CAMERA")!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{"android.permission.CAMERA"},9);else openCamera();});}
 void openCamera(){startActivityForResult(new Intent(MediaStore.ACTION_IMAGE_CAPTURE),10);}
 @Override protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(r==10&&c==RESULT_OK&&d!=null&&d.getExtras()!=null&&d.getExtras().get("data") instanceof Bitmap){Bitmap bm=(Bitmap)d.getExtras().get("data");recognize(bm);} }
 void recognize(Bitmap bm){ui("🔎 Проверяем: "+targetObject);root.addView(text("Распознавание…",18));ImageLabeling.getClient(ImageLabelerOptions.DEFAULT_OPTIONS).process(InputImage.fromBitmap(bm,0)).addOnSuccessListener(labels->{boolean ok=false;for(ImageLabel l:labels){String x=l.getText().toLowerCase(Locale.ROOT);if(matches(targetObject,x)){ok=true;break;}}if(ok){root.addView(text("✅ Предмет распознан!",20));new Handler().postDelayed(this::next,500);}else{root.addView(text("❌ Не удалось уверенно распознать предмет. Сфотографируй ещё раз крупнее и целиком.",18));Button again=b("📷 Ещё фото");root.addView(again);again.setOnClickListener(v->openCamera());if(getSharedPreferences("bell",0).getBoolean("hasReference",false)){root.addView(text("Есть эталонное фото: попробуй снять предмет с похожего ракурса.",16));}}}).addOnFailureListener(e->{root.addView(text("Распознавание недоступно. Сфотографируй предмет ещё раз.",18));Button again=b("📷 Ещё фото");root.addView(again);again.setOnClickListener(v->openCamera());});}
 boolean matches(String target,String label){String t=target.toLowerCase(Locale.ROOT);if(t.equals("холодильник"))return label.contains("refrigerator")||label.contains("fridge");if(t.equals("микроволновка"))return label.contains("microwave");if(t.equals("стол"))return label.contains("table")||label.contains("desk");if(t.equals("кофеварка"))return label.contains("coffee")||label.contains("espresso");if(t.equals("телевизор"))return label.contains("television")||label.contains("tv");if(t.equals("стул"))return label.contains("chair");if(t.equals("дверь"))return label.contains("door");if(t.equals("лампа"))return label.contains("lamp")||label.contains("lighting");return false;}
 @Override public void onRequestPermissionsResult(int r,String[]p,int[]g){super.onRequestPermissionsResult(r,p,g);if(r==9&&g.length>0&&g[0]==PackageManager.PERMISSION_GRANTED)openCamera();}
 void memory(){ui("🧠 Память");root.addView(text("Запомни 6 зелёных плиток, затем нажми их по порядку.",17));LinearLayout grid=new LinearLayout(this);grid.setOrientation(LinearLayout.VERTICAL);root.addView(grid);ArrayList<Button>bs=new ArrayList<>();for(int row=0;row<3;row++){LinearLayout rr=new LinearLayout(this);grid.addView(rr);for(int col=0;col<4;col++){Button q=b("□");rr.addView(q,new LinearLayout.LayoutParams(0,90,1));bs.add(q);}}ArrayList<Integer>seq=new ArrayList<>();while(seq.size()<6){int x=random.nextInt(12);if(!seq.contains(x))seq.add(x);}new Handler().postDelayed(()->{for(int x:seq)bs.get(x).setText("🟩");new Handler().postDelayed(()->{for(Button q:bs)q.setText("□");final int[]k={0};for(Button q:bs)q.setOnClickListener(v->{int x=bs.indexOf(v);if(x==seq.get(k[0])){k[0]++;if(k[0]==6)next();}else{Toast.makeText(this,"Неверно — попробуй снова",Toast.LENGTH_SHORT).show();k[0]=0;}});},1300);},500);}
 void reaction(){ui("⚡ Реакция");TextView t=text("Жди…",22);root.addView(t);Button hit=b("НЕ НАЖИМАТЬ");root.addView(hit);hit.setEnabled(false);new Handler().postDelayed(()->{t.setText("🟢 СЕЙЧАС!");hit.setEnabled(true);long st=System.currentTimeMillis();hit.setOnClickListener(v->{Toast.makeText(this,(System.currentTimeMillis()-st)+" мс",Toast.LENGTH_SHORT).show();next();});},1200+random.nextInt(2800));}
 void sequence(){ui("🔢 Порядок");root.addView(text("Нажми числа от 1 до 10 по порядку.",18));ArrayList<Integer>a=new ArrayList<>();for(int i=1;i<=10;i++)a.add(i);Collections.shuffle(a);GridLayout g=new GridLayout(this);g.setColumnCount(2);root.addView(g);final int[]n={1};for(int x:a){Button q=b(String.valueOf(x));g.addView(q,new ViewGroup.LayoutParams(220,80));q.setOnClickListener(v->{if(Integer.parseInt(q.getText().toString())==n[0]){q.setEnabled(false);n[0]++;if(n[0]==11)next();}else Toast.makeText(this,"Нужна цифра "+n[0],Toast.LENGTH_SHORT).show();});}}
 void colorTask(){ui("🎨 Цвет");String[]names={"КРАСНЫЙ","СИНИЙ","ЗЕЛЁНЫЙ","ЖЁЛТЫЙ"};int[]cols={Color.RED,Color.BLUE,Color.GREEN,Color.YELLOW};for(int k=0;k<5;k++){int target=random.nextInt(4);TextView q=text("Найди: "+names[target],20);root.addView(q);LinearLayout row=new LinearLayout(this);root.addView(row);final boolean[]done={false};for(int j=0;j<4;j++){Button x=b(names[j]);x.setTextColor(Color.BLACK);x.setBackgroundColor(cols[j]);row.addView(x,new LinearLayout.LayoutParams(0,70,1));final int jj=j;x.setOnClickListener(v->{if(jj==target){done[0]=true;q.setText("✓ "+names[target]);for(int z=0;z<row.getChildCount();z++)row.getChildAt(z).setEnabled(false);}});}}Button done=b("Готово");root.addView(done);done.setOnClickListener(v->{next();});}
 void shake(){ui("📳 Тряска");root.addView(text("Потряси телефон 8 раз.",20));sm=(SensorManager)getSystemService(SENSOR_SERVICE);Sensor s=sm.getDefaultSensor(Sensor.TYPE_ACCELEROMETER);if(s!=null)sm.registerListener(this,s,SensorManager.SENSOR_DELAY_GAME);}
 int shakes=0;@Override public void onSensorChanged(SensorEvent e){float g=(float)Math.sqrt(e.values[0]*e.values[0]+e.values[1]*e.values[1]+e.values[2]*e.values[2]);if(g>18&&System.currentTimeMillis()-lastShake>350){lastShake=System.currentTimeMillis();shakes++;title.setText("📳 Тряска: "+shakes+"/8");if(shakes>=8){sm.unregisterListener(this);next();}}}@Override public void onAccuracyChanged(Sensor s,int a){}
 void finishChallenge(){ui("🔒 Будильник разблокирован");title.setGravity(Gravity.CENTER);title.setTextSize(30);TextView lock=text("🔒",72);lock.setGravity(Gravity.CENTER);root.addView(lock,new LinearLayout.LayoutParams(-1,0,1));TextView msg=text("Все задания пройдены.\nСлой сейчас откроется — теперь можно выключить обычный будильник в приложении «Часы».",20);msg.setGravity(Gravity.CENTER);root.addView(msg);new Handler().postDelayed(()->{lock.animate().rotation(20).setDuration(180).withEndAction(()->lock.animate().rotation(-20).setDuration(180).withEndAction(()->lock.animate().rotation(0).setDuration(180).withEndAction(()->{lock.setText("🔓");new Handler().postDelayed(this::finish,500);}))).start();},500);}
}
