package com.yarikfanfarik.veryhardbell;
import android.app.*;import android.content.*;import android.os.*;import android.provider.Settings;import android.graphics.*;import android.view.*;import android.widget.*;import java.util.*;

public class MainActivity extends Activity{
 static final String[] TASKS={"FLAPPY — 10 зелёных труб","Математика — 5 примеров","Фото предмета","Память — 6 плиток","Реакция","Порядок — 1→10","Цвет","Тряска"};
 static final String KEY_ORDER="order",KEY_ENABLED="enabled",KEY_DIFF="diff"; SharedPreferences p;LinearLayout root;
 public void onCreate(Bundle b){super.onCreate(b);p=getSharedPreferences("bell",0);showHome();}
 TextView tv(String s,int z){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setPadding(20,16,20,16);return t;} Button btn(String s){Button b=new Button(this);b.setText(s);return b;}
 void base(String title){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(18,18,18,18);root.addView(tv(title,26));ScrollView sv=new ScrollView(this);sv.addView(root);setContentView(sv);}
 String nextAlarm(){AlarmManager am=(AlarmManager)getSystemService(ALARM_SERVICE);if(am==null)return "нет данных";AlarmManager.AlarmClockInfo x=am.getNextAlarmClock();if(x==null)return "будильник не найден";Calendar c=Calendar.getInstance();c.setTimeInMillis(x.getTriggerTime());return String.format(Locale.getDefault(),"%02d:%02d",c.get(Calendar.HOUR_OF_DAY),c.get(Calendar.MINUTE));}
 void showHome(){base("⏰ Very Hard Bell");root.addView(tv("Приложение больше НЕ ставит свой будильник. Ты ставишь обычный будильник в приложении «Часы», а Very Hard Bell реагирует на выбранное время.",17));root.addView(tv("Следующий системный будильник: "+nextAlarm(),19));Button a=btn("🎯 Выбрать, на какой будильник реагировать");root.addView(a);a.setOnClickListener(v->systemAlarmSettings());Button t=btn("🎯 Задания, порядок и сложность");root.addView(t);t.setOnClickListener(v->taskSettings());Button o=btn("🧊 Предметы для фото");root.addView(o);o.setOnClickListener(v->objectSettings());Button test=btn("▶ Тест испытания сейчас");root.addView(test);test.setOnClickListener(v->startActivity(new Intent(this,AlarmActivity.class)));if(Build.VERSION.SDK_INT>=31){Button ex=btn("Разрешение точного будильника");root.addView(ex);ex.setOnClickListener(v->{try{startActivity(new Intent(Settings.ACTION_REQUEST_SCHEDULE_EXACT_ALARM));}catch(Exception ignored){}});}}
 void systemAlarmSettings(){base("🎯 Системный будильник");root.addView(tv("Поставь обычный будильник в приложении «Часы». Здесь укажи его время. Если следующий системный будильник имеет это время, приложение запустит испытание поверх экрана.",16));EditText h=new EditText(this);h.setHint("Часы, например 07");h.setInputType(2);root.addView(h);EditText m=new EditText(this);m.setHint("Минуты, например 30");m.setInputType(2);root.addView(m);String cur=nextAlarm();if(cur.matches("\\d{2}:\\d{2}")){h.setText(cur.substring(0,2));m.setText(cur.substring(3));}Button save=btn("💾 Сохранить и синхронизировать");root.addView(save);save.setOnClickListener(v->{try{int hh=Integer.parseInt(h.getText().toString()),mm=Integer.parseInt(m.getText().toString());if(hh<0||hh>23||mm<0||mm>59)throw new Exception();p.edit().putInt("systemHour",hh).putInt("systemMinute",mm).apply();AlarmReceiver.schedule(this);Toast.makeText(this,"Реакция настроена на "+String.format(Locale.getDefault(),"%02d:%02d",hh,mm),Toast.LENGTH_SHORT).show();showHome();}catch(Exception e){Toast.makeText(this,"Введи время 00–23 и минуты 00–59",Toast.LENGTH_SHORT).show();}});Button back=btn("Назад");root.addView(back);back.setOnClickListener(v->showHome());}
 ArrayList<Integer> order(){String s=p.getString(KEY_ORDER,"0,1,2,3,4,5,6,7");ArrayList<Integer>a=new ArrayList<>();for(String x:s.split(","))try{a.add(Integer.parseInt(x));}catch(Exception e){}return a;}void saveOrder(ArrayList<Integer>a){StringBuilder s=new StringBuilder();for(int x:a){if(s.length()>0)s.append(',');s.append(x);}p.edit().putString(KEY_ORDER,s.toString()).apply();}
 void taskSettings(){base("🎯 Задания");root.addView(tv("Можно отключать и менять порядок. Сложность: легко / нормально / сложнее.",16));ArrayList<Integer>a=order();boolean[]en=new boolean[8];String es=p.getString(KEY_ENABLED,"11111111");for(int i=0;i<8;i++)en[i]=i<es.length()&&es.charAt(i)=='1';LinearLayout list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);root.addView(list);refreshTaskList(list,a,en);Spinner diff=new Spinner(this);String[]ds={"Легко","Нормально","Сложнее"};diff.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,ds));diff.setSelection(p.getInt(KEY_DIFF,0));root.addView(tv("Сложность",16));root.addView(diff);Button save=btn("💾 Сохранить");root.addView(save);save.setOnClickListener(v->{StringBuilder s=new StringBuilder();for(boolean q:en)s.append(q?'1':'0');p.edit().putString(KEY_ENABLED,s.toString()).putInt(KEY_DIFF,diff.getSelectedItemPosition()).apply();saveOrder(a);showHome();});Button back=btn("Назад");root.addView(back);back.setOnClickListener(v->showHome());}
 void refreshTaskList(LinearLayout list,ArrayList<Integer>a,boolean[]en){list.removeAllViews();for(int pos=0;pos<a.size();pos++){final int idx=pos,task=a.get(pos);LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);CheckBox c=new CheckBox(this);c.setText(TASKS[task]);c.setChecked(en[task]);c.setLayoutParams(new LinearLayout.LayoutParams(0,-2,1));c.setOnCheckedChangeListener((b,x)->en[task]=x);row.addView(c);Button up=btn("↑"),dn=btn("↓");row.addView(up,new LinearLayout.LayoutParams(55,55));row.addView(dn,new LinearLayout.LayoutParams(55,55));up.setOnClickListener(v->{if(idx>0){Collections.swap(a,idx,idx-1);refreshTaskList(list,a,en);}});dn.setOnClickListener(v->{if(idx<a.size()-1){Collections.swap(a,idx,idx+1);refreshTaskList(list,a,en);}});list.addView(row);}}
 void objectSettings(){base("🧊 Предметы для фото");root.addView(tv("Случайный предмет выбирается из отмеченных. Для встроенных предметов используется распознавание ML Kit. Если объект не распознан, можно сделать эталонное фото — тогда проверяем похожесть фото.",16));String[] names={"Холодильник","Микроволновка","Стол","Кофеварка","Телевизор","Стул","Дверь","Лампа"};String old=p.getString("objects","11111111");for(int i=0;i<names.length;i++){CheckBox c=new CheckBox(this);c.setText(names[i]);c.setChecked(old.charAt(i)=='1');c.setTag(i);root.addView(c);}Button ref=btn("📷 Сделать эталонное фото");root.addView(ref);ref.setOnClickListener(v->startActivityForResult(new Intent(MediaStore.ACTION_IMAGE_CAPTURE),77));Button save=btn("💾 Сохранить список");root.addView(save);save.setOnClickListener(v->{StringBuilder s=new StringBuilder();for(int i=0;i<names.length;i++){CheckBox c=(CheckBox)root.findViewWithTag(i);s.append(c.isChecked()?'1':'0');}if(s.toString().equals("00000000"))s.replace(0,1,"1");p.edit().putString("objects",s.toString()).apply();showHome();});Button back=btn("Назад");root.addView(back);back.setOnClickListener(v->showHome());}
 @Override protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(r==77&&c==RESULT_OK&&d!=null&&d.getExtras()!=null&&d.getExtras().get("data") instanceof Bitmap){Bitmap b=(Bitmap)d.getExtras().get("data");getSharedPreferences("bell",0).edit().putBoolean("hasReference",true).putInt("referenceColor",averageColor(b)).apply();Toast.makeText(this,"Эталон сохранён",Toast.LENGTH_SHORT).show();}}
 int averageColor(Bitmap b){Bitmap x=Bitmap.createScaledBitmap(b,1,1,true);return x.getPixel(0,0);}
}
